name: 'complete ci-cd'

on:
  push:
    branches: [devops]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Frontend install
      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      # Backend install
      - name: Install backend dependencies
        run: npm install
        working-directory: backend

      # Run frontend lint
      - name: Run frontend lint
        run: npx eslint .
        working-directory: frontend

      # Run backend lint
      - name: Run backend lint
        run: npx eslint .
        working-directory: backend
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
